# Generated by Django 4.2.5 on 2023-09-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employee_dismissal_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.CharField(verbose_name='Дата рождения'),
        ),
    ]
