# Generated by Django 4.2.5 on 2023-09-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_employee_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dismissal_date',
            field=models.CharField(default='работает по настоящее время', verbose_name='Дата увольнения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='slug',
            field=models.CharField(default='employee', verbose_name='Уникальное название'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(default='активен', verbose_name='Статус'),
        ),
    ]
