# Generated by Django 4.2.5 on 2023-09-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_employee_dismissal_date_alter_employee_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(verbose_name='Разряд'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='number',
            field=models.CharField(verbose_name='Личный №'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(verbose_name='Штатная позиция'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.CharField(verbose_name='Бригада №'),
        ),
    ]
