# Generated by Django 4.2.5 on 2023-10-24 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_employee_dismissal_date_alter_employee_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='area',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='category',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dismissal_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employment_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
    ]
