# Generated by Django 4.2.5 on 2023-10-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_employee_area_remove_employee_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='surname',
        ),
        migrations.AddField(
            model_name='employee',
            name='fullname',
            field=models.CharField(default='', verbose_name='ФИО'),
        ),
    ]
