# Generated by Django 4.2.5 on 2023-10-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_employee_name_remove_employee_patronymic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fullname',
            field=models.CharField(verbose_name='ФИО'),
        ),
    ]
