# Generated by Django 4.2.5 on 2023-10-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_employee_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(verbose_name='Дата')),
                ('shift', models.CharField(verbose_name='Смена')),
                ('team', models.CharField(verbose_name='Бригада')),
                ('report', models.TextField(verbose_name='Табель')),
            ],
            options={
                'verbose_name_plural': 'Табель',
            },
        ),
    ]
