# Generated by Django 4.2.5 on 2023-10-31 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_timesheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='report',
            new_name='timesheet',
        ),
    ]
