# Generated by Django 4.2.5 on 2023-10-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_report_timesheet_timesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='idProfession',
            field=models.CharField(default='', verbose_name='Номер профессии'),
        ),
    ]
