# Generated by Django 4.2.5 on 2023-10-31 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_employee_idprofession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='idProfession',
            new_name='number',
        ),
    ]
