# Generated by Django 4.2.5 on 2023-10-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_idprofession_employee_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='number',
            field=models.CharField(verbose_name='Номер профессии'),
        ),
    ]
