# Generated by Django 4.2.5 on 2023-10-31 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_employee_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='number',
        ),
    ]
