# Generated by Django 4.2.5 on 2023-10-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_employee_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='number',
            field=models.CharField(default='', verbose_name='Номер сортировки'),
        ),
    ]
