# Generated by Django 4.2.5 on 2023-11-01 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_employee_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='date',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='shift',
        ),
    ]
