# Generated by Django 4.2.5 on 2023-11-01 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_timesheet_date_remove_timesheet_shift'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSheet',
        ),
    ]
