# Generated by Django 4.2.5 on 2023-11-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_delete_timesheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(verbose_name='Бригада')),
                ('timesheet', models.TextField(verbose_name='Табель')),
            ],
            options={
                'verbose_name_plural': 'Табель',
            },
        ),
    ]
