# Generated by Django 4.2.5 on 2023-11-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_timesheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='number',
        ),
        migrations.AddField(
            model_name='employee',
            name='schedule',
            field=models.CharField(default='', verbose_name='График работы'),
        ),
    ]
