# Generated by Django 4.2.5 on 2023-11-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_employee_number_employee_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='schedule',
            field=models.CharField(verbose_name='График работы'),
        ),
    ]
