# Generated by Django 4.2.5 on 2023-11-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_employee_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='area',
            field=models.CharField(default='ЛПЦ-5', verbose_name='Участок'),
        ),
        migrations.AddField(
            model_name='employee',
            name='presence',
            field=models.CharField(default='ЯВКА', verbose_name='Присутствие на рабочем месте'),
        ),
    ]
