# Generated by Django 4.2.5 on 2023-11-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_employee_area_employee_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='area',
            field=models.CharField(verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='presence',
            field=models.CharField(verbose_name='Присутствие на рабочем месте'),
        ),
    ]
