# Generated by Django 4.2.5 on 2023-11-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_employee_area_alter_employee_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='numeric',
            field=models.CharField(default='', verbose_name='Номер сортировки'),
        ),
    ]
