# Generated by Django 4.2.5 on 2023-11-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_employee_numeric'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='probation',
            field=models.CharField(default='', verbose_name='Стажировка'),
        ),
    ]
