# Generated by Django 4.2.5 on 2023-11-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_employee_probation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='probation',
            field=models.CharField(default='ПРОЙДЕНА', verbose_name='Стажировка'),
        ),
    ]
