# Generated by Django 4.2.5 on 2023-11-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_employee_probation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='probation',
            field=models.CharField(verbose_name='Стажировка'),
        ),
    ]
