# Generated by Django 4.2.5 on 2023-11-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_employee_probation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='area',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='login',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='numeric',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='presence',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='probation',
        ),
    ]
