# Generated by Django 4.2.5 on 2023-11-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_remove_employee_area_remove_employee_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='numeric',
            field=models.CharField(default='', verbose_name='Номер сортировки'),
        ),
    ]
