# Generated by Django 4.2.5 on 2023-11-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_employee_numeric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='numeric',
            field=models.CharField(verbose_name='Номер сортировки'),
        ),
    ]
