# Generated by Django 4.2.5 on 2023-10-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(verbose_name='Партия')),
                ('number', models.CharField(verbose_name='Номер')),
            ],
            options={
                'verbose_name_plural': 'Продукция',
            },
        ),
    ]
