# Generated by Django 4.2.5 on 2023-10-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(verbose_name='Дата')),
                ('shift', models.CharField(verbose_name='Смена')),
                ('team', models.CharField(verbose_name='Бригада')),
                ('area', models.CharField(verbose_name='Участок')),
                ('unit', models.CharField(verbose_name='Единица измерения')),
                ('plan', models.CharField(verbose_name='План')),
                ('residue', models.CharField(verbose_name='Остаток')),
            ],
        ),
    ]
