# Generated by Django 4.2.5 on 2023-10-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name_plural': 'Рапорт'},
        ),
        migrations.RemoveField(
            model_name='report',
            name='area',
        ),
        migrations.RemoveField(
            model_name='report',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='report',
            name='residue',
        ),
        migrations.RemoveField(
            model_name='report',
            name='unit',
        ),
        migrations.AddField(
            model_name='report',
            name='report',
            field=models.TextField(default='', verbose_name='Участок'),
        ),
    ]
