# Generated by Django 4.2.5 on 2023-10-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_report_options_remove_report_area_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
