# Generated by Django 4.2.5 on 2023-10-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0004_delete_product_delete_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(verbose_name='Уникальное название')),
                ('title', models.CharField(verbose_name='Название участка')),
                ('unit', models.CharField(verbose_name='Единица измерения показателя')),
                ('plan', models.CharField(verbose_name='Планируемое производство')),
                ('residue', models.CharField(verbose_name='Остаток по смене')),
            ],
            options={
                'verbose_name_plural': 'Участки',
            },
        ),
    ]
