# Generated by Django 4.2.5 on 2023-10-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='plan',
            field=models.CharField(default='', verbose_name='Планируемое производство'),
        ),
        migrations.AlterField(
            model_name='area',
            name='residue',
            field=models.CharField(default='', verbose_name='Остаток по смене'),
        ),
    ]
