# Generated by Django 4.2.5 on 2023-10-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_remove_area_plan_remove_area_residue'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='plan',
            field=models.IntegerField(default=0, verbose_name='Планируемое производство'),
        ),
        migrations.AddField(
            model_name='area',
            name='residue',
            field=models.IntegerField(default=0, verbose_name='Остаток по смене'),
        ),
    ]
