# Generated by Django 4.2.5 on 2023-10-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_area_plan_area_residue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(verbose_name='Дата')),
                ('shift', models.CharField(verbose_name='Смена')),
                ('team', models.CharField(verbose_name='Бригада')),
            ],
            options={
                'verbose_name_plural': 'Дата',
            },
        ),
    ]
