# Generated by Django 4.2.5 on 2023-10-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='slug',
            field=models.CharField(default='', verbose_name='Уникальное название'),
        ),
    ]
