# Generated by Django 4.2.5 on 2023-10-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_profession_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='slug',
            field=models.CharField(verbose_name='Уникальное название'),
        ),
    ]
