# Generated by Django 4.2.5 on 2023-10-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_alter_profession_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='area',
            name='residue',
        ),
    ]
