# Generated by Django 4.2.5 on 2023-10-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_remove_area_plan_remove_area_residue'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='report',
            field=models.TextField(default='', verbose_name='Рапорт'),
        ),
    ]
