# Generated by Django 4.2.5 on 2023-11-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_report_delete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='plan',
            field=models.CharField(default='', verbose_name='План'),
        ),
        migrations.AddField(
            model_name='area',
            name='residue',
            field=models.CharField(default='', verbose_name='Остаток'),
        ),
    ]
