# Generated by Django 4.2.5 on 2023-11-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_area_plan_area_residue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='plan',
            field=models.CharField(verbose_name='План'),
        ),
        migrations.AlterField(
            model_name='area',
            name='residue',
            field=models.CharField(verbose_name='Остаток'),
        ),
    ]
