# Generated by Django 4.2.5 on 2023-11-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_alter_area_plan_alter_area_residue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='plan',
            field=models.CharField(default='', verbose_name='План'),
        ),
        migrations.AlterField(
            model_name='area',
            name='residue',
            field=models.CharField(default='', verbose_name='Остаток'),
        ),
    ]
