# Generated by Django 4.2.5 on 2023-11-18 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0031_alter_area_plan_alter_area_residue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='area',
            name='residue',
        ),
    ]
