# Generated by Django 4.2.5 on 2023-11-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0035_remove_area_plan_remove_area_residue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='unit',
            field=models.CharField(default='', verbose_name='Единица измерения показателя'),
        ),
    ]
