# Generated by Django 4.2.5 on 2023-11-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0036_area_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='unit',
            field=models.CharField(verbose_name='Единица измерения показателя'),
        ),
    ]
